settings:
  title: '网站状态检测'
  url: 'cf-workers-status-page-production.vikimlee.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 365 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统正常运行'
  notAllmonitorsOperational: '并非所有系统都运行正常'
  monitorLabelOperational: '正常运转'
  monitorLabelNotOperational: '不正常运转'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '健康'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded
  
  - id: cmer-hkcmereye # unique identifier
    name: Eye center
    description: '眼科中心官网' # default=empty
    url: 'https://www.hkcmereye.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

